name: native_video_player_example
description: Demonstrates how to use the native_video_player plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  native_video_player:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/video/
